const fs = require("fs");
// ATENCAO: este script sobrescreve login_page.dart.
// Se voce alterar login_page.dart diretamente, regenere este script antes de executa-lo.
const code = [
'import "dart:async";',
'import "package:flutter/material.dart";',
'import "package:shared_preferences/shared_preferences.dart";',
'import "package:http/http.dart" as http;',
'import "dart:convert";',
'import "dashboard_page.dart";',
'',
'class LoginPage extends StatefulWidget {',
'  @override',
'  _LoginPageState createState() => _LoginPageState();',
'}',
'',
'class _LoginPageState extends State<LoginPage> {',
'  final TextEditingController userController = TextEditingController();',
'  final TextEditingController passController = TextEditingController();',
'  bool isLoading = false;',
'',
'  // URL do painel - troque para seu dominio quando publicar online',
'  final String panelUrl = "http://192.168.1.132:3000";',
'  final String fallbackUrl = "http://observacaoonline.pro";',
'',
'  Future<void> login() async {',
'    setState(() { isLoading = true; });',
'    try {',
'      final String user = userController.text.trim();',
'      final String pass = passController.text.trim();',
'      if (user.isEmpty || pass.isEmpty) {',
'        showError("Preencha usuario e senha");',
'        setState(() { isLoading = false; });',
'        return;',
'      }',
'',
'      String baseUrl = fallbackUrl;',
'',
'      // Busca a URL do cliente especifico no painel',
'      try {',
'        final authResponse = await http.post(',
'          Uri.parse("${panelUrl}/api/auth/app"),',
'          headers: {"Content-Type": "application/json"},',
'          body: jsonEncode({"username": user, "password": pass}),',
'        ).timeout(const Duration(seconds: 5));',
'',
'        if (authResponse.statusCode == 200) {',
'          final authData = jsonDecode(authResponse.body);',
'          if (authData["xtreamUrl"] != null && authData["xtreamUrl"].isNotEmpty) {',
'            baseUrl = authData["xtreamUrl"];',
'          }',
'        } else if (authResponse.statusCode == 403) {',
'          showError("Acesso bloqueado ou expirado. Contate o suporte.");',
'          setState(() { isLoading = false; });',
'          return;',
'        } else if (authResponse.statusCode == 404) {',
'          // Cliente nao cadastrado no painel, usa fallback',
'          baseUrl = fallbackUrl;',
'        }',
'      } catch (e) {',
'        // Painel offline, usa fallback',
'        baseUrl = fallbackUrl;',
'      }',
'',
'      // Autentica no servidor Xtream',
'      http.Response response;',
'      try {',
'        response = await http.get(',
'          Uri.parse("${baseUrl}/player_api.php?username=${user}&password=${pass}"),',
'        ).timeout(const Duration(seconds: 15));',
'      } on TimeoutException {',
'        showError("Servidor IPTV demorou demais para responder. Tente novamente.");',
'        return;',
'      } catch (e) {',
'        showError("Erro de conexao com o servidor IPTV: ${e.toString()}");',
'        return;',
'      }',
'',
'      if (response.statusCode != 200) {',
'        showError("Servidor IPTV indisponivel (${response.statusCode}). Tente novamente em instantes.");',
'        return;',
'      }',
'',
'      final Map<String, dynamic> data;',
'      try {',
'        data = jsonDecode(response.body);',
'      } catch (_) {',
'        showError("Resposta invalida do servidor IPTV. Tente novamente.");',
'        return;',
'      }',
'',
'      if (data["user_info"] == null) {',
'        showError("Usuario ou senha invalidos");',
'        return;',
'      }',
'',
'      final prefs = await SharedPreferences.getInstance();',
'      await prefs.setString("xtream_url", baseUrl);',
'      await prefs.setString("xtream_user", user);',
'      await prefs.setString("xtream_pass", pass);',
'      if (mounted) Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => DashboardPage()));',
'    } catch (e) {',
'      showError("Erro de conexao: Verifique sua internet (${e.toString()})");',
'    } finally {',
'      if (mounted) setState(() { isLoading = false; });',
'    }',
'  }',
'',
'  void showError(String msg) {',
'    ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(msg), backgroundColor: Colors.red));',
'  }',
'',
'  @override',
'  Widget build(BuildContext context) {',
'    return Scaffold(',
'      backgroundColor: Colors.black,',
'      body: Center(',
'        child: SingleChildScrollView(',
'          padding: const EdgeInsets.all(32),',
'          child: Column(',
'            mainAxisAlignment: MainAxisAlignment.center,',
'            children: [',
'              const Icon(Icons.play_circle_fill, size: 100, color: Colors.red),',
'              const SizedBox(height: 10),',
'              const Text("Center Play", style: TextStyle(fontSize: 36, color: Colors.red, fontWeight: FontWeight.bold, letterSpacing: 1.5)),',
'              const SizedBox(height: 8),',
'              const Text("Seu entretenimento em um lugar", style: TextStyle(color: Colors.grey, fontSize: 14)),',
'              const SizedBox(height: 50),',
'              TextField(',
'                controller: userController,',
'                style: const TextStyle(color: Colors.white),',
'                decoration: const InputDecoration(',
'                  labelText: "Usuario",',
'                  labelStyle: TextStyle(color: Colors.grey),',
'                  filled: true, fillColor: Color(0xFF141414),',
'                  border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(8)), borderSide: BorderSide.none),',
'                  prefixIcon: Icon(Icons.person, color: Colors.grey),',
'                ),',
'              ),',
'              const SizedBox(height: 16),',
'              TextField(',
'                controller: passController,',
'                obscureText: true,',
'                style: const TextStyle(color: Colors.white),',
'                onSubmitted: (_) => login(),',
'                decoration: const InputDecoration(',
'                  labelText: "Senha",',
'                  labelStyle: TextStyle(color: Colors.grey),',
'                  filled: true, fillColor: Color(0xFF141414),',
'                  border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(8)), borderSide: BorderSide.none),',
'                  prefixIcon: Icon(Icons.lock, color: Colors.grey),',
'                ),',
'              ),',
'              const SizedBox(height: 32),',
'              SizedBox(',
'                width: double.infinity, height: 55,',
'                child: ElevatedButton(',
'                  onPressed: isLoading ? null : login,',
'                  style: ElevatedButton.styleFrom(backgroundColor: Colors.red, shape: const RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(8)))),',
'                  child: isLoading ? const CircularProgressIndicator(color: Colors.white) : const Text("Entrar", style: TextStyle(fontSize: 18, color: Colors.white, fontWeight: FontWeight.bold)),',
'                ),',
'              ),',
'            ],',
'          ),',
'        ),',
'      ),',
'    );',
'  }',
'}',
].join("\n");
fs.writeFileSync("C:/Users/LENOVO/Documents/meu-projeto/iptv_app/lib/login_page.dart", code, {encoding:"utf8"});
console.log("Done");
