const fs = require("fs");
const lines = [
"generator client {",
"  provider = \"prisma-client-js\"",
"}",
"",
"datasource db {",
"  provider = \"sqlite\"",
"  url      = \"file:./dev.db\"",
"}",
"",
"model AdminUser {",
"  id        String   @id @default(cuid())",
"  username  String   @unique",
"  password  String",
"  createdAt DateTime @default(now())",
"  updatedAt DateTime @updatedAt",
"}",
"",
"model Client {",
"  id        String   @id @default(cuid())",
"  username  String   @unique",
"  password  String",
"  name      String?",
"  xtreamUrl String",
"  isActive  Boolean  @default(true)",
"  expiresAt DateTime?",
"  notes     String?",
"  createdAt DateTime @default(now())",
"  updatedAt DateTime @updatedAt",
"}",
"",
"model AppSettings {",
"  id            String   @id @default(cuid())",
"  xtreamUrl     String",
"  globalMessage String?",
"  updatedAt     DateTime @updatedAt",
"}",
];
fs.writeFileSync("prisma/schema.prisma", lines.join("\n"), {encoding:"utf8"});
console.log("Done");
